package battleships.config.websocket;

import lombok.Getter;

import java.security.Principal;


@Getter
public class CustomPrincipal implements Principal {

    private final String name;
    private final boolean autoGenerated;


    public CustomPrincipal(String name, boolean autoGenerated) {
        this.name = name;
        this.autoGenerated = autoGenerated;
    }

}
