package battleships.config.websocket;

import battleships.domain.user.AnonymousUser;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.web.socket.WebSocketHandler;
import org.springframework.web.socket.server.support.DefaultHandshakeHandler;

import java.security.Principal;
import java.util.Map;

public class CustomHandshakeHandler extends DefaultHandshakeHandler {

    /**
     * @param request
     * @param wsHandler
     * @param attributes
     * @return Custom Principal with unique username for guest instead of returning null
     */


    /*
    @Override
    protected Principal determineUser(ServerHttpRequest request, WebSocketHandler wsHandler, Map<String, Object> attributes) {
        Principal principal = request.getPrincipal();
        if (principal == null) return AnonymousUser.newAutoGeneratedUser();
        return new CustomPrincipal(principal.getName(), false);
    }
    */
}
