package battleships.domain.user;

import java.util.UUID;


/**
 * Custom principal with name and information if user is guest or logged in
 */
public class AnonymousUser extends AbstractUser {

    private final String name;


    private AnonymousUser(String name, boolean autoGenerated) {
        super(true);
        this.name = name;
    }

    public static AnonymousUser newAutoGeneratedUser() {
        return new AnonymousUser("AUTO" + UUID.randomUUID().toString(), true);
    }


    @Override
    public UserRole getRole() {
        return UserRole.GUEST;
    }

    @Override
    public String getPassword() {
        return null;
    }

    @Override
    public String getUsername() {
        return name;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
